#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("P8_Beacon_App.Resource", IsApplication=true)]

namespace P8_Beacon_App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Refractored.Xam.Vibrate.Resource.String.ApplicationName = global::P8_Beacon_App.Resource.String.ApplicationName;
			global::Refractored.Xam.Vibrate.Resource.String.Hello = global::P8_Beacon_App.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060015
			public const int MyButton = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int button1 = 2131099667;
			
			// aapt resource value: 0x7f060005
			public const int button4 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int button5 = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int button6 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int gridLayout1 = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int plot_view = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int spinner1 = 2131099666;
			
			// aapt resource value: 0x7f060009
			public const int textView10 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int textView11 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int textView12 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int textView13 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int textView14 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int textView15 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int textView16 = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int textView2 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int textView3 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int textView4 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int textView5 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int textView6 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int textView8 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int textView9 = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layout2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int ApplicationName = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int Hello = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int ToActivity2 = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int error_no_bluetooth_enabled = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int error_no_bluetooth_le = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int error_no_location_permission = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int requesting_location_access = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int requesting_location_access_cancel = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int requesting_location_access_ok = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int requesting_location_access_rationale = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int requesting_location_permission = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int requesting_location_permission_rationale = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Transparent = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
